spring:
  datasource:
    url: jdbc:mysql://mysql:3306/release-tracker?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: default
      database-platform: org.hibernate.dialect.MySQLDialect
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always